- name: Launch Nginx reverse proxy
  docker_container:
    name: proxy
    image: victorbucas/tp-devops-http:latest
    state: started
    restart_policy: always
    networks:
      - name: my_network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./proxy/conf:/etc/nginx/conf.d:ro
