name: CI/CD DevOps 2025

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  test-simpleapi:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build and test with Maven
        run: mvn clean verify -DskipITs
        working-directory: TP1/simpleapi

      - name: Build and test with Sonar
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=Brmstone_docker-lab -Dsonar.organization=brmstone -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}  --file ./pom.xml
        working-directory: TP1/simpleapi

  build-and-push-docker-image:
    needs: test-simpleapi
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build image and push backend
        uses: docker/build-push-action@v6
        with:
          context: TP1/simpleapi
          tags: ${{secrets.DOCKER_USERNAME}}/tp-devops-simple-api:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push database
        uses: docker/build-push-action@v6
        with:
          context: TP1
          tags:  ${{secrets.DOCKER_USERNAME}}/tp-devops-database:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push httpd
        uses: docker/build-push-action@v6
        with:
          context: TP1/http
          tags:  ${{secrets.DOCKER_USERNAME}}/tp-devops-http:latest
          push: ${{ github.ref == 'refs/heads/main' }}
