name: CI/CD DevOps 2025

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build and test with Maven
        run: mvn clean verify -DskipITs
        working-directory: TP1/simpleapi

      - name: Show test failure reports (if any)
        if: failure()
        run: |
          echo "=== FAILSAFE REPORTS ==="
          cat TP1/simpleapi/target/failsafe-reports/*.txt || true
          echo "=== SUREFIRE REPORTS ==="
          cat TP1/simpleapi/target/surefire-reports/*.txt || true
